amazonProperties:
  endpointUrl: https://ec2-35-177-156-144.eu-west-2.compute.amazonaws.com
  accessKey: AKIAVIWZLBLMIJO22J4T
  secretKey: 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
  bucketName: web-stell-searcher
  clientRegion: Region.EU_London
